### Header ###
title: theme-kaze demo
author: theme-kaze
logo_img: /img/Kaze.png # put the logo on the ${blog_path}/source/img/${picname}.png or use urls
author_img: /img/Kaze.png
author_description: designed by theme-kaze
### navebar ###
menus:
  Home: /
  Archives: /archives
  About: /about
  Friends: /links
rss: /atom.xml

# Content
fancybox: true

### Sidebar ###
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

### Links ###
links: 
  friend:
    url: /
    img: 
  # name1:
  #   url: https://example.com
  #   img: 



### Post ###
post:
  # Please use <!-- more --> in the post to set the length of excerpt mannually
  # and will overwite the configuration here.
  excerpt_length: 120
  #
  excerpt_link: Read More

### Footer ###
footer:
  copy_year: 2019
  # if showPoweredBy is ture, 'Powered by Hexo' will be seen on the footer
  showPoweredBy: true
  # if showDesignedBy is ture, 'Designed by 0x4qE/songhn' will be seen on the footer
  showDesignedBy: true

### Up to top ###
# if scrollUpAnimation is true, there will be scroll-up animation.
scrollUpAnimation: false

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# the config of theme colors and styles
# you can modify these presets to design different styles
color:
  text-color: "#3c4858"
  text-strong-color: "#2f3d4e"
  text-light-color: "#909faf"
  divider-color: "#e6e8ee"
  title-color: "#475b6d"
  link-color: "#3273dc"
  link-hover-color: "#6596e5"
  info-text-color: "#909faf"
  widget-background-color: "#fff"
  body-background-color: "#f2f5f8"

font:
  font-size: 16px # global font-size
  font-family: # global font-family