### Header ###
title: 0x4qE's Blog
author: 0x4qE
logo_path: /img/Kaze.png # put the logo on the ${blog_path}/source/img/${picname}.png

### navebar ###
menus:
  Home: /
  Archives: /archives
  About: /about
  Friends: /links
rss: /atom.xml

# Content
fancybox: true

### Sidebar ###
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

### Links ###
links: 
  friend:
    url: /
    img: 
  # name1:
  #   url: https://example.com
  #   img: 



### Post ###
post:
  # Please use <!-- more --> in the post to set the length of excerpt mannually
  # and will overwite the configuration here.
  excerpt_length: 120
  #
  excerpt_link: Read More

### Footer ###
footer:
  copy_year: 2019
  # if showPoweredBy is ture, 'Powered by Hexo' will be seen on the footer
  showPoweredBy: true
  # if showDesignedBy is ture, 'Designed by 0x4qE/songhn' will be seen on the footer
  showDesignedBy: true

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
