### Header ###
title: theme-kaze demo
author: theme-kaze
logo_img: /img/Kaze.png # put the logo on the ${blog_path}/source/img/${picname}.png or use urls
author_img: /img/Kaze.png
author_description: designed by theme-kaze
### navebar ###
menus:
  home: /
  archive: /archives
  tags: /tags
  categories: /categories
  about: /about
  friends: /links

page:
  # about page config
  about:
    description: description
    social_links:
      - { icon: icon-icon-test5, link: https://github.com }
      - { icon: icon-icon-test, link: / }
      - { icon: icon-icon-test1, link: / }
      - { icon: icon-icon-test4, link: / }

# Content
fancybox: true

### Sidebar ###
sidebar: right
widgets:
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

### Links ###
links:
  friend1:
    url: /
    avatar: /img/Kaze.png
    description: test1
  friend2:
    url: /
    avatar: /img/Kaze.png
    description: test2
  friend3:
    url: /
    avatar: /img/Kaze.png
    description: test3
  # name1:
  #   url: https://example.com
  #   avatar:

### Post ###
post:
  # Please use <!-- more --> in the post to set the length of excerpt mannually
  # and will overwite the configuration here.
  excerpt_length: 120

### Footer ###
footer:
  copy_year: 2019
  # if showPoweredBy is ture, 'Powered by Hexo' will be seen on the footer
  showPoweredBy: true
  # if showThemeName is ture, 'Theme - Kaze' will be seen on the footer
  showThemeName: true

### Up to top ###
# if scrollUpAnimation is true, there will be scroll-up animation.
scrollUpAnimation: true

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: "monthly"
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# latex config
# choose true to use latex by mathjax or katex
latex:
  enable: true
  engine: katex # mathjax/katex
  # for better rendering effect, when you choose mathjax, you can use it directly but you will lose some effect
  # so you can use hexo-renderer-kramed
  # when you choose katex, you must use hexo-renderer-markdown-it-plus or other render engine
  global: true
  # because latex rendering is too expensive for page loading
  # so when you choose false, you can use latex by `latex: true` in post front-matter

# the config of theme colors and styles
# you can modify these presets to design different styles
color:
  text-color: "#3c4858"
  text-strong-color: "#2f3d4e"
  text-light-color: "#909faf"
  divider-color: "#e6e8ee"
  title-color: "#475b6d"
  link-color: "#3273dc"
  link-hover-color: "#6596e5"
  info-text-color: "#909faf"
  widget-background-color: "#fff"
  body-background-color: "#f2f5f8"
  border-color: "#e1e4e9"
  pre-color: "#f4f5f7"
  code-color: "#50687c"
  code-background-color: "#e9eaf0"

font:
  font-size: 16px # global font-size
  font-family: # global font-family
